export const POPULAR_BRANDS = [
  'Absolute',
  'Apreamare',
  'Aquila',
  'Astondoa',
  'Atlantis',
  'Axopar',
  'Azimut',
  'Baglietto',
  'Bali',
  'Bavaria',
  'Bayliner',
  'Beneteau',
  'Benetti',
  'Boston Whaler',
  'Brig',
  'Capelli',
  'Carver',
  'Catana',
  'Chaparral',
  'Chris-Craft',
  'Cobalt',
  'Cranchi',
  'Crownline',
  'Custom Line',
  'Dehler',
  'Dufour',
  'Elan',
  'Enma Marine',
  'Excess',
  'Fairline',
  'Ferretti',
  'Fjord',
  'Fountaine Pajot',
  'Four Winns',
  'Frauscher',
  'Galeon',
  'Grand',
  'Grand Banks',
  'Grand Soleil',
  'Greenline',
  'Hallberg-Rassy',
  'Hanse',
  'Highfield',
  'Invictus',
  'Isatek',
  'Jeanneau',
  'Joker Boat',
  'Karnic',
  'Lagoon',
  'Leopard',
  'Linssen',
  'Maiora',
  'Mangusta',
  'MasterCraft',
  'Mazu Yachts',
  'Mengi Yay',
  'Mercury',
  'Monterey',
  'Moody',
  'Nautique',
  'Nautor Swan',
  'Nautitech',
  'Nimbus',
  'Northstar',
  'Numarine',
  'Ocean Alexander',
  'Outremer',
  'Oyster',
  'Pardo Yachts',
  'Pershing',
  'Prestige',
  'Princess',
  'Quicksilver',
  'Regal',
  'Riva',
  'Rinker',
  'Rota Marine',
  'Safter',
  'Sanlorenzo',
  'Saxdor',
  'Scanner',
  'Sea Ray',
  'Sea-Doo',
  'Sealine',
  'Sessa Marine',
  'Sirena Yachts',
  'Solaris',
  'Sunreef',
  'Sunseeker',
  'Tiara',
  'Turquoise Yachts',
  'Vicem Yachts',
  'Viking',
  'Wally',
  'Wellcraft',
  'Williams Jet Tenders',
  'Windy',
  'X-Yachts',
  'Yamaha',
  'Yerliyurt',
  'Zar Formenti',
  'Zodiac'
];
